---
title: "Biaxial sleepwalk test"
output: html_document
date: "2024-04-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r functions}
setwd(here::here("src"))
source("knn_sleepwalk.R")
```

Here, we're going to test a modification of sleepwalk that compares a biaxial plot to its corresponding region on a UMAP. Let's load the CyTOF data.

```{r get_data}
library(tidyverse)
library(here)
library(flowCore)
library(sleepwalk)
set.seed(1)

setwd(here::here('data'))

# Read in the cells
cells <- flowCore::read.FCS(list.files(pattern = "SLE")) # Data from Marie Burns
params <- as.vector(Biobase::pData(parameters(cells))$desc)
colnames(cells) <- params
cells <- exprs(cells) 
cells <- cells[, grepl("CD", colnames(cells))] # A shortcut to get to the surface markers we care about
cells <- asinh(cells/5) %>% as_tibble()

num_cells <- 20000
cells <- cells[sample(nrow(cells), num_cells),]
cells
```

Ok, now let's make our UMAP.

```{r run_dimr}
library(umap)

umap <- umap::umap(cells)$layout %>% as_tibble()
umap
```
And now for the sleepwalk hack.

```{r}
setwd(here::here("output"))

biaxial <- bind_cols(cells["195Pt_CD3"], cells["143Nd_CD19"])

KnnSleepwalk(mat = biaxial, embedding = list(biaxial, umap), k = 50, output_file = paste0("knn_sleepwalk_biaxial_test", "_", num_cells, ".html"), point_size = 4, dimr_names = c("", ""))
```


