---
title: "How to use the KNN sleepwalk wrapper"
output: html_notebook
---

This code tests the wrapper function for a KNN-based sleepwalk.

```{r functions}
source('../src/knn_sleepwalk.R')
```


```{r get_data}
library(tidyverse)
library(here)
library(flowCore)
library(sleepwalk)
set.seed(1)

setwd(here::here('data'))

# Read in the cells
cells <- flowCore::read.FCS(list.files(pattern = "SLE")) # Data from Marie Burns
params <- as.vector(Biobase::pData(parameters(cells))$desc)
colnames(cells) <- params
cells <- exprs(cells) 
cells <- cells[, grepl("CD", colnames(cells))] # A shortcut to get to the surface markers we care about
cells <- asinh(cells/5) %>% as_tibble()
cells <- cells[sample(nrow(cells), 4000),]
cells
```

```{r run_dimr}
library(umap)
library(Rtsne)

umap <- umap::umap(cells)$layout %>% as_tibble()
tsne <- Rtsne::Rtsne(X = cells)$Y %>% as_tibble()
```

```{r run_knn_sleepwalk}
setwd(here::here("output"))
KnnSleepwalk(mat = cells, embedding = list(tsne, umap), k = 40, output_file = "knn_sleepwalk_cytof.html")
KfnSleepwalk(mat = cells, embedding = list(tsne, umap), k = 400, output_file = "kfn_sleepwalk_cytof.html")
```

