---
title: "Make small dataset for R package"
output: html_document
date: "2024-05-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This markdown simply takes the data we have been using, and makes a small dataset for the unit testing for the package.

```{r functions}
source('src/knn_sleepwalk.R')
```


```{r get_data}
library(tidyverse)
library(here)
library(flowCore)
library(sleepwalk)
set.seed(1)

setwd(here::here('data'))

# Read in the cells
cells <- flowCore::read.FCS(list.files(pattern = "SLE")) # Data from Marie Burns
params <- as.vector(Biobase::pData(parameters(cells))$desc)
colnames(cells) <- params
cells <- exprs(cells) 
cells <- cells[,!is.na(colnames(cells))]
cells <- as_tibble(cells)

# Filter the cells by marker we're going to use
marker_info <- readr::read_csv("cytof_marker_data.csv")
marker_info <- dplyr::filter(marker_info, is.na(notes)) # Take this out later

# Subsample
num_cells <- 1000
cells <- cells[sample(nrow(cells), num_cells),]
cells

# Tranform the markers we want to transform
to_transform <- dplyr::filter(marker_info, marker_type != "none")$desc
keep_same <- dplyr::filter(marker_info, marker_type == "none")$desc %>% .[!is.na(.)]

tmp1 <- cells[,to_transform]
tmp2 <- cells[,keep_same]

tmp1 <- asinh(tmp1/5)
cells <- bind_cols(tmp1, tmp2)
```

```{r run_dimr}
library(umap)
library(Rtsne)

surface <- cells[,dplyr::filter(marker_info, marker_type == "type")$desc]
umap <- umap::umap(surface, preserve.seed = FALSE)$layout %>% as_tibble()
names(umap) <- c("umap1", "umap2")
```

```{r}
setwd(here::here("output", "week_of_may_6_2024"))

save(surface, file = "surface_markers_ExpT35_SLE_R_pool_2_HC13_HC_comp_99p_95p.rda")
save(umap, file = "umap_ExpT35_SLE_R_pool_2_HC13_HC_comp_99p_95p.rda")
```

